regenerate_lovelace:
  name: Regenerate Lovelace files
  description: Regenerates the Lovelace files for each LockSmithy lock. Lovelace files are already regenerated every time the LockSmithy Configuration or Options are changed and whenever Home Assistant restarts. In general, this action does not need to be manually run. LockSmithy lovelace files are located in /custom_components/locksmithy/lovelace

update_pin:
  name: Update PIN in a Code Slot
  description: Update PIN for a Code Slot in a LockSmithy lock
  fields:
    config_entry_id:
      name: Lock
      description: The lock to Update the PIN in
      required: true
      selector:
        config_entry:
          integration: locksmithy
    code_slot_num:
      name: Code Slot
      description: The code slot to update the PIN in
      example: 2
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: box
    pin:
      name: PIN
      description: The PIN to set (Must be 4 or more digits)
      example: 1234
      required: true
      selector:
        text:

clear_pin:
  name: Clear PIN from a Code Slot
  description: Clear PIN for a Code Slot in a LockSmithy lock
  fields:
    config_entry_id:
      name: Lock
      description: The lock to clear the PIN from
      required: true
      selector:
        config_entry:
          integration: locksmithy
    code_slot_num:
      name: Code Slot
      description: The code slot to clear the PIN from
      required: true
      example: 2
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: box

import_from_keymaster:
  name: Import from keymaster
  description: Import keymaster details into a LockSmithy lock
  fields:
    config_entry_id:
      name: LockSmithy Lock
      description: The LockSmithy lock to import the keymaster lock details into
      required: true
      selector:
        config_entry:
          integration: locksmithy
    keymaster_config_entry_id:
      name: keymaster Lock
      description: The keymaster lock details to export
      required: true
      selector:
        config_entry:
          integration: keymaster
    delete_package_files:
      name: Delete Package Files
      description: Delete package files for selected keymaster lock
      required: true
      default: true
      selector:
        boolean:
